### ISSUE TITLE
$400 for this is a scam 

### ISSUE THREAD

**Issue by aithedev** [abdallah34/Tiktok-Api#1]
literally so easy to get bro

**Comment by standfv** [comment]
aithedev you scammer.
![9A6E8A2B-271B-4EE6-82DF-0E70DA185DC6](https://user-images.githubusercontent.com/27364465/215154867-b30dcebe-c1ec-46ae-b4ff-2b67334dcf6b.jpeg)
![20454521-0EAF-4F55-AA11-4F93679E8955](https://user-images.githubusercontent.com/27364465/215154884-24b8ddd8-fee7-4d3d-92f5-3f6931416c4d.png)
